### ISSUE TITLE
Buffs (Such as Renew, POM) not showing on left of spells

### ISSUE THREAD

**Issue by jamesmonnier** [Toludin/Healium#1]
Hello: First of all, thank you so much for helping us healers out and making the updates. I Tried and failed horribly. 

I did download and replace the addon files with the ones you provided, however, the buffs bar is not working for me. Any thoughts?

Thanks - Daminion

**Comment by Toludin** [comment]
Whoops. Should be fixed. This is why I have people familiar with the addon test ;-)

**Comment by jamesmonnier** [comment]
Thank you so much... It is showing the buffs for me and i posted your link on the addon site

https://www.curseforge.com/wow/addons/healium

Thanks again - you rock

**Comment by jamesmonnier** [comment]
So far.. the only thing i see is that "Ray of Hope" is showing the wrong Icon when being applied .
It's really not a big deal but that is what my initial testing has shown.

Note: I have only tested Holy Pally and Holy Priest at the moment but will try to check Druid and Disc Priest soon.

**Comment by Toludin** [comment]
Does Ray of Hope look like this?

https://bfa.wowhead.com/spell=232707/ray-of-hope

Looks like the buff icon might just be that one instead of the actual casted spell's icon. A few are like this, unfortunately. I could look into a one-off exception for that one (manually assigning it the normal Ray of Hope icon) but might get out of hand if a lot come up like this.

**Comment by Toludin** [comment]
Just checked and verified that the Ray of Hope buff in Healium does match the actual Ray of Hope buff put on the target in game. Bit annoying that Blizzard didn't make them match, but it does look like this is functioning correctly.

Let me know if you see any other issues though!
