### ISSUE TITLE
Magic debuff do not appear for Monk heal

### ISSUE THREAD

**Issue by Ouranos16** [Toludin/Healium#10]
Hello,
After doing some dungeon, I do not see when a player have a magic debuff that work fine for other type of debuff.

Could you please help ?

Thanks

PS: I love this addon :)

**Comment by Toludin** [comment]
Thanks for the report - I'll look into this. Just to make sure I'm understanding correctly - your Monk doesn't show magic debuff highlighting, but does show poison and disease debuff highlighting? And have you seen if other healers magic debuff highlighting works?

I have a feeling this is because Detox is the name of the spell for both Mistweaver and Brewmaster/Windwalker, and the one for BrM/WW doesn't dispel magic.

**Comment by Toludin** [comment]
This should be fixed in the latest build.
