### ISSUE TITLE
Parties go missing periodically

### ISSUE THREAD

**Issue by omegaxnodle** [Toludin/Healium#2]
First thanks again for all the effort you have put in to making Healium still have life. One problem I run into is when logging in or periodically thought the game the parties will go missing. This can be resolved by doing a /reloadui command. I have tested with ElvUi and others UIs as well with the same results. Thanks again for all the work you do. I am hoping you turn this into your own add-on in the future.

**Comment by Toludin** [comment]
Yea, I've noticed this as well and been trying to track it down. Well, I haven't actually done much in parties yet so I haven't seen it disappear during a group, but I know it doesn't show on log-in. That's actually really interesting to know that it's occurring outside of the initial log-in event.

Can you shed any light as to when this happens when you're in parties, or playing the game? Anything you can remember about people joining/leaving, how many people there were, etc? No worries if not, but anything you can remember (or gather moving forward) would be helpful.

Also, at least for the log-in issue, I noticed you could fit it by just double-clicking the Healium button (to hide and then show all frames). Bit quicker than a /reload. Can you try this when it disappears in normal play and let me know if it recovers the party frames for that as well?

**Comment by omegaxnodle** [comment]
I have noticed it on log in and after leaving a dungeon or raid group that it happens. So must be related to the loading screen. I will try the button trick when I get home from work tonight.

**Comment by Toludin** [comment]
In some local testing, I deleted almost every change I've made to the addon (just keeping changes to let the addon load in the first place, which were minimal) and this issue still occurs. So while I'm lightly patting myself on the back that I didn't introduce this issue, it seems that something else changing in the API has had this effect on Healium.

That does unfortunately mean it'll take a bit longer for me to find, most likely (since I can't narrow it down just to the changes I've made).

One thing I noticed is that, while the issue pops up 100% of the time when I log into the game, it won't happen if I'm logging in while already in a group.

**Comment by Toludin** [comment]
Alright, I have a rather...brute force possible fix that I'd appreciate some folks trying out in groups and such. I know it fixes the on-login issue but would like to see if it causes any other issues, and if it fixes the leaving-raid or leaving-party problems.

If you're up for trying it, please download the latest and give it a whirl. Please let me know if you run into any issues, where they cropped up, and what went wrong. Thanks in advance!

**Comment by omegaxnodle** [comment]
Thanks so much, I will try when I get home tonight and report back to you. Are you taking new suggestions for this add-on as well? I hope you are taking it over since it's been abandoned.

**Comment by Toludin** [comment]
I mostly just took on Healium (and a few other addons) that I noticed people were asking for updates on, and brought them forward to 8.0. I didn't have significant plans for adding features, but I'd be happy to consider any additions people are looking for. Not sure I'll be able to implement them, but willing to try.

I'll likely be putting this up on Curseforge as 'Healium Reborn' or something pretty soon. I reached out to the author a bit ago asking if I could push an update to users, but I've not gotten a response yet.

**Comment by omegaxnodle** [comment]
Great to hear, I like the name 'Healium Reborn'. Make sure to put up a donation thing, I know many will donate to the cause. Also I went home for lunch as was able to try the new version, and everything is working perfectly. So it looks like it's fixed. As for suggestions:

-This is more visual, but I know when Atonements are on your self and a shield they line up properly on the left side in line with the nameplate/health bar. But when placing a shield on another party member the mana bar slightly covers the shield and Atonements. Not a huge deal breaker. I can get you a screenshot if you would like.

- One suggestion as another player recommend here: http://i.imgur.com/rqAithY.jpg

It would be nice to customize the appearance more such as a drop down for different textures shown as some recommend in the image above. Right now the only way its gets changed is if you use ELVui and Addon skins it does change it, but it also removes the mini role icons such as tank/healer/dps. If you use elvui and addon skins you would see what I am talking about. Again these are just future ideas, we are all just happy to have a working addon. Looking forward to seeing it on Curse that way you can push out updates to it. Thanks again for all the hard work!

**Comment by Toludin** [comment]
Awesome, thanks for those suggestions. I'm going to open new issues for each so I can mark them as feature requests so they can be documented, and close out this issue since it looks like it's fixed.

Just fyi, I took another look at the addon on Curse and noticed that the author has set the license to 'All Rights Reserved.' I'm not a lawyer, so I don't know the legal realities of any of it, but in my mind at least that means he or she doesn't want people creating derivative works without his or her approval. So unfortunately, until I get approval from the author, I don't feel comfortable making a new version of the addon and expanding it. I did find an email address as well for them and reached out that way, so I'm hopeful I can either get Maintainer status on the original addon or get their approval to make a new version, but for now at least I'm going to keep this to just bug fixes to allow those with the addon to keep using it.

I'd still love to hear any ideas for additions and improvements that people have, in preparation for (hopefully) being able to make them.

Thanks!
Toludin
