### ISSUE TITLE
Helium updated in Twitch/curse?

### ISSUE THREAD

**Issue by lynspottery** [Toludin/Healium#31]
I use Helium for my Shaman and love it.  I started using it on my Bal Druid to do spot heals to help out and have really enjoyed how it operates.

However, after Bliz's patch yesterday and Twitch's update yesterday evening, it appears to have updated (or over written) the download I used from this site to keep my copy current.

Has your situation changed from what you have posted on this site? 

> Because the addon author published Healium as 'all rights reserved,' Twitch/Curse will not host my version as a 'Healium Continued' or similar style continuation. I tried and they explicitly told me this, so unfortunately this repository will be the only source for these changes for the time being.

**Comment by hannahxxashley** [comment]
Do you use automatic updates for your addons through Twitch? A couple of months ago, Twitch kept asking me if I wanted to let them manage Healium, as they had found a similar file for it or something like that. I clicked yes, thinking maybe the person that has been pushing the new updates through gitub was finally able to host on Twitch or something but all it did was overwrite my files that I downloaded from this github and replaced them with the garbage out of date files that Twitch has on file for Healium and then this caused my addon to not work in game. 
So I went to Twitch and selected “Ignore” on the Healium addon (I think you just right click Healium in your addon list and there should be an option to ignore). This way, Twitch will no longer alert me to any updates or try to update the addon. So then I just downloaded the github files again and replaced the out of date files that Twitch had put back in place and everything worked again. And now I don’t have to worry about it because Twitch is ignoring that addon so it won’t overwrite any manual updates I put in place. 

Hope this helps!

**Comment by Toludin** [comment]
Unfortunately, to my knowledge at least, nothing has changed on the Twitch/Curse side of things. I can't host this new version on their site as engypoo has listed it as all right reserved, and obviously this version is heavily based off of his version. I'd love to get it up there so fans can get the updates automatically, but I'm afraid it's just not something I can control.

**Comment by lynspottery** [comment]
Thank you very much for this response.  I was unaware of the ignore option on Twitch and constantly was redoing everything manually....appreciate it.
